## Validate the corrected state-based phenotypic score.
##
## P_s(state)   = mean(S over team1) - mean(S over team2)      [no /N]
## top30/top60  = basin-weighted MEAN of P_s over the states making up the
##                top 30% / 60% of the state space by basin size
##
## The published `_stateps` columns were generated by older code that divided
## by the network node count, so we check `new == old * N` for the dominant
## state and report the relationship for the aggregates.
repo <- getwd(); options(interactingteams.repo = repo)
source(file.path(repo, "Metrics", "metrics_lib.R"))

truth <- read.csv(file.path(repo,"Combined_data","combined_module_level_data.csv"),
                  stringsAsFactors = FALSE)
truth <- truth[truth$pheno_score_method == "stateps" & truth$l_max == 1, ]

freq_file <- function(net) {
  for (d in c("Two_module_nets", NETWORK_DIR)) {
    p <- file.path(repo, d, paste0(net, "_finFlagFreq.csv"))
    if (file.exists(p)) return(p)
  }
  NA_character_
}

domN <- c(ok = 0, tot = 0); ratios <- list()
for (net in unique(truth$network_name)) {
  fp <- freq_file(net); if (is.na(fp)) next
  tp  <- find_net_file(repo, net, "topo")
  nds <- read_nodes(file.path(dirname(tp), paste0(net, "_nodes.txt")))
  N   <- length(nds)
  for (m in modules_of(net)) {
    if (!has_two_teams(repo, m)) next
    mt  <- restrict_teams(module_teams(repo, m), nds)
    agg <- aggregate_ps(state_ps_table(fp, nds, mt), normalise = TRUE)
    r   <- truth[truth$network_name == net & truth$module_abbr == m, ]
    if (!nrow(r)) next
    domN["tot"] <- domN["tot"] + 1
    if (abs(agg[["dominant"]] - r$P_s_dominant[1] * N) < 1e-9)
      domN["ok"] <- domN["ok"] + 1
    for (k in c("top30","top60"))
      ratios[[k]] <- c(ratios[[k]], agg[[k]] / (r[[paste0("P_s_",k)]][1] * N))
  }
}
cat("\n=== corrected state-based P_s vs published `_stateps` (lmax1)\n")
cat(sprintf("  dominant == published * N_network : %d / %d\n", domN["ok"], domN["tot"]))
for (k in c("top30","top60")) {
  v <- ratios[[k]][is.finite(ratios[[k]])]
  cat(sprintf("  %s ratio (new / (published*N)): median %.3f, IQR [%.3f, %.3f]  -> not a constant factor\n",
      k, median(v), quantile(v, .25), quantile(v, .75)))
}
